import { Award, FileCheck, Download } from 'lucide-react';
import { useI18n } from '../i18n';

const Qualita = () => {
  const { language } = useI18n();
  const t = {
    it: { title: 'Qualita e Omologazioni', sub: 'The quality of made in Italy', h: 'Sistema di Gestione Qualita', p1: 'SMA ha un sistema certificato ISO 9001:2015.', table: 'Conformita e Omologazioni', b: 'Scarica Certificato', note: 'Tutti i prodotti SMA sono marcati CE.' },
    en: { title: 'Quality and Approvals', sub: 'The quality of made in Italy', h: 'Quality Management System', p1: 'SMA has an ISO 9001:2015 certified management system.', table: 'Compliance and Approvals', b: 'Download Certificate', note: 'All SMA products are CE marked.' },
    de: { title: 'Qualitaet und Zulassungen', sub: 'The quality of made in Italy', h: 'Qualitaetsmanagementsystem', p1: 'SMA besitzt ein nach ISO 9001:2015 zertifiziertes Managementsystem.', table: 'Konformitaet und Zulassungen', b: 'Zertifikat herunterladen', note: 'Alle SMA-Produkte sind CE-gekennzeichnet.' },
  }[language];

  return (
    <main className="pt-[104px]"><section className="relative h-[400px] overflow-hidden"><div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: 'url(/images/hero-tank-1.jpg)' }}><div className="absolute inset-0 bg-black/60" /></div><div className="relative h-full container mx-auto px-4 flex items-center"><div className="max-w-2xl text-white"><h1 className="text-5xl font-bold mb-4">{t.title}</h1><p className="text-xl text-gray-200">{t.sub}</p></div></div></section><section className="py-16 bg-white"><div className="container mx-auto px-4 grid lg:grid-cols-3 gap-12"><div className="bg-gray-50 p-6 rounded-2xl h-fit"><div className="w-16 h-16 bg-[#b91c1c] rounded-full flex items-center justify-center mb-6"><Award className="w-8 h-8 text-white" /></div><h3 className="text-xl font-bold text-gray-900 mb-4">{t.h}</h3><p className="text-gray-600 mb-6">{t.p1}</p><a href="/original-site/ISO9001.pdf" className="inline-flex items-center gap-2 px-6 py-3 bg-[#b91c1c] text-white font-medium rounded-lg hover:bg-[#991b1b] transition-all"><Download className="w-5 h-5" />{t.b}</a></div><div className="lg:col-span-2"><h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3"><FileCheck className="w-7 h-7 text-[#b91c1c]" />{t.table}</h2><div className="overflow-x-auto"><table className="w-full border-collapse"><thead><tr className="bg-gray-100"><th className="text-left p-4">{language === 'it' ? 'Tipologia' : language === 'en' ? 'Type' : 'Typ'}</th><th className="text-left p-4">{language === 'it' ? 'Riferimento' : language === 'en' ? 'Directive' : 'Richtlinie'}</th><th className="text-left p-4">{language === 'it' ? 'Norme' : language === 'en' ? 'Norms' : 'Normen'}</th></tr></thead><tbody><tr className="border-b"><td className="p-4">{language === 'it' ? 'Serbatoi in pressione stradali' : language === 'en' ? 'Road pressure tanks' : 'Strassen-Druckbehaelter'}</td><td className="p-4">2014/29/UE</td><td className="p-4">EN286/2</td></tr><tr className="border-b"><td className="p-4">{language === 'it' ? 'Serbatoi ferroviari' : language === 'en' ? 'Rail tanks' : 'Schienenbehaelter'}</td><td className="p-4">2014/29/UE</td><td className="p-4">EN286/4</td></tr><tr className="border-b"><td className="p-4">{language === 'it' ? 'Serbatoi PED' : language === 'en' ? 'PED tanks' : 'PED-Behaelter'}</td><td className="p-4">2014/68/UE</td><td className="p-4">EN13445</td></tr></tbody></table></div><div className="mt-8 p-6 bg-amber-50 rounded-xl border border-amber-200"><p className="text-amber-800 font-medium">{t.note}</p></div></div></div></section></main>
  );
};

export default Qualita;
